# Generated by Django 5.0.1 on 2024-01-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='language',
            field=models.CharField(default='English', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=30),
            preserve_default=False,
        ),
    ]
